Update Makefile.docs-bi-connector

diff --git a/makefiles/Makefile.docs-bi-connector b/makefiles/Makefile.docs-bi-connector
--- a/makefiles/Makefile.docs-bi-connector
+++ b/makefiles/Makefile.docs-bi-connector
@@ -29,7 +29,14 @@ html: ## Builds this branch's HTML under build/<branch>/html
 next-gen-html:
 	# snooty parse and then build-front-end
 	curl https://raw.githubusercontent.com/mongodb/docs-worker-pool/meta/publishedbranches/docs-bi-connector.yaml > ${REPO_DIR}/published-branches.yaml
-	@echo ${SNOOTY_DB_PWD} | snooty build "${REPO_DIR}" "mongodb+srv://${SNOOTY_DB_USR}:@cluster0-ylwlz.mongodb.net/snooty?retryWrites=true" --commit "${COMMIT_HASH}"; if [$$? -eq 1]; then exit 1; else exit 0; fi
+	@echo ${SNOOTY_DB_PWD} | snooty build "${REPO_DIR}" "mongodb+srv://${SNOOTY_DB_USR}:@cluster0-ylwlz.mongodb.net/snooty?retryWrites=true" --commit "${COMMIT_HASH}"; \
+            if [ $$? -eq 1 ]; then \
+	    	echo "FAIL"; \
+                exit 1; \
+            else \
+                echo "PASS"; \
+		exit 0; \
+            fi
 	cp -r ${REPO_DIR}/../../snooty ${REPO_DIR};
 	cd snooty; \
 	echo "GATSBY_SITE=${PROJECT}" > .env.production; \
@@ -38,6 +45,7 @@ next-gen-html:
 	echo "COMMIT_HASH=${COMMIT_HASH}" >> .env.production; \
 	npm run build; \
 	cp -r "${REPO_DIR}/snooty/public" ${REPO_DIR};
+	
 
 STABLE_BRANCH_NEXT_GEN = `grep 'manual' ${REPO_DIR}/published-branches.yaml | cut -d ':' -f 2 | grep -Eo '[0-9a-z.]+'`
 
