Update Makefile.docs-bi-connector

diff --git a/makefiles/Makefile.docs-bi-connector b/makefiles/Makefile.docs-bi-connector
--- a/makefiles/Makefile.docs-bi-connector
+++ b/makefiles/Makefile.docs-bi-connector
@@ -30,19 +30,19 @@ next-gen-html:
 	# snooty parse and then build-front-end
 	curl https://raw.githubusercontent.com/mongodb/docs-worker-pool/meta/publishedbranches/docs-bi-connector.yaml > ${REPO_DIR}/published-branches.yaml
 	@echo ${SNOOTY_DB_PWD} | snooty build "${REPO_DIR}" "mongodb+srv://${SNOOTY_DB_USR}:@cluster0-ylwlz.mongodb.net/snooty?retryWrites=true" --commit "${COMMIT_HASH}"; \
-            if [ $? -eq 0 ]; then \
-	    	echo "PASS"; \
-                exit 0; \
-            if [ $? -eq 2]; then \
-            	echo "PASS 2"; \
-		exit 0; \
-            if [ $? -eq 1]; then
-	    	echo "FAIL 1 "; \
-		exit 1; \
-            else \
-	    	echo "NOT EQUAL TO THIS"; \
-		exit 0; \
-            fi
+		if [ $? -eq 0 ]; then \
+			echo "PASS 0"; \
+			exit 0; \
+		if [ $? -eq 2]; then \
+			echo "PASS 2"; \
+			exit 0; \
+		if [ $? -eq 1]; then
+			echo "FAIL 1 "; \
+			exit 1; \
+		else \
+			echo "NOT EQUAL TO THIS"; \
+			exit 0; \
+		fi
 	cp -r ${REPO_DIR}/../../snooty ${REPO_DIR};
 	cd snooty; \
 	echo "GATSBY_SITE=${PROJECT}" > .env.production; \
